[package]
name = "rustic_calculator"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.69"
inquire = "0.5.3"
meval = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


